version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    env_file: .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_HOSTNAME
      - KC_DB
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KC_DB_URL_DATABASE
      - KC_DB_URL_HOST
      - KC_DB_URL_PORT
    env_file: .env.prod
    ports:
      - "443:8443"
    volumes:
      - keycloak-data:/var/lib/keycloak/data

volumes:
  postgres-data: {}
  keycloak-data: {}
