version: "3.8"

services:
  keycloak-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    env_file: .env
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    depends_on:
      - keycloak-postgres
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_HOSTNAME
      - KC_DB
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
      - KC_DB_URL_DATABASE
      - KC_DB_URL_HOST
      - KC_DB_URL_PORT
    env_file: .env
    restart: unless-stopped`
    volumes:
      - keycloak-data:/var/lib/keycloak/data
  nginx:
    image: ghcr.io/table-side/iam-nginx:main
    environment:
      - KEYCLOAK_HOST
      - KEYCLOAK_PORT
      - KEYCLOAK_DOMAIN
      - LE_EMAIL
      - LE_OPTIONS
      - LE_RENEW_OPTIONS
      - LE_RENEW_CRON_COMMAND
    env_file: .env
    depends_on:
      - keycloak
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - keycloak-nginx-data:/etc/letsencrypt

volumes:
  keycloak-postgres-data: {}
  keycloak-data: {}
  keycloak-nginx-data: {}
