version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
    env_file: .env
    ports:
      - "8040:8080"
    volumes:
      - keycloak-data:/var/lib/keycloak/data

volumes:
  postgres-data: {}
  keycloak-data: {}
